name: Poll Helldivers API and Cache Data

on:
  schedule:
    # Runs at every 10th minute
    - cron: '*/10 * * * *'

jobs:
  cache-planet-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install jq for JSON parsing
        run: sudo apt-get install jq

      - name: Fetch current war season
        id: fetch-season
        run: |
          CURRENT_SEASON=$(curl -s "https://helldivers-2.fly.dev/api" | jq -r '.current')
          echo "::set-output name=current_season::$CURRENT_SEASON"
      
      - name: Fetch planet statuses and save with timestamp
        run: |
          mkdir -p data
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          FILENAME="data/${TIMESTAMP}_planet_statuses.json"
          curl "https://helldivers-2.fly.dev/api/${{ steps.fetch-season.outputs.current_season }}/status" -o "$FILENAME"

      - name: Cleanup old data files
        run: |
          find data/ -type f -name '*_planet_statuses.json' -mmin +720 -delete

      - name: Fetch feed data and save with timestamp
        run: |
          mkdir -p feed
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          FILENAME="feed/${TIMESTAMP}_feed.json"
          curl "https://helldivers-2.fly.dev/api/${{ steps.fetch-season.outputs.current_season }}/feed" -o "$FILENAME"

      - name: Cleanup old feed files in /feed
        run: |
          find feed/ -type f -name '*_feed.json' -mmin +40 -delete

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions Bot"
          git add data/ feed/
          git commit -m "Update data for war season ${{ steps.fetch-season.outputs.current_season }}" -a || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.ACTION_BOT_KEY }}@github.com/devpoole2907/helldivers-api-cache.git
          git push






