name: Poll Helldivers API and Cache Data

on:
  schedule:
    # Runs at every 10th minute
    - cron: '*/10 * * * *'

jobs:
  cache-planet-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install jq for JSON parsing
        run: sudo apt-get install jq

      - name: Fetch current war season
        id: fetch-season
        run: |
          CURRENT_SEASON=$(curl -s "https://helldivers-2.fly.dev/api" | jq -r '.current')
          echo "::set-output name=current_season::$CURRENT_SEASON"

      - name: Fetch planet statuses from Helldivers API and save with timestamp
        run: |
          mkdir -p data # Ensure the directory exists
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          curl "https://helldivers-2.fly.dev/api/${{ steps.fetch-season.outputs.current_season }}/status" -o "data/${TIMESTAMP}_planet_statuses.json"
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions Bot"
          git add data/
          git commit -m "Update planet statuses for war season ${{ steps.fetch-season.outputs.current_season }}" -a || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.ACTION_BOT_KEY }}@github.com/devpoole2907/helldivers-api-cache.git
          git push

