name: Poll Helldivers API and Cache Data

on:
  schedule:
    # Runs at every 10th minute
    - cron: '*/10 * * * *'

jobs:
  cache-planet-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install jq for JSON parsing
        run: sudo apt-get install jq

      - name: Fetch current war season
        id: fetch-season
        run: |
          CURRENT_SEASON=$(curl -s "https://helldivers-2.fly.dev/api" | jq -r '.current')
          echo "::set-output name=current_season::$CURRENT_SEASON"
      
      - name: Fetch planet statuses and save with timestamp
        run: |
          mkdir -p data
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          FILENAME="data/${TIMESTAMP}_planet_statuses.json"
          curl "https://helldivers-2.fly.dev/api/${{ steps.fetch-season.outputs.current_season }}/status" -o "$FILENAME"

      - name: Cleanup old data files
        run: |
          # Define the current date and time
          current_time=$(date -u +%s)

          # Loop through each file in the data directory
          for file in data/*_planet_statuses.json; do
              # Extract the timestamp from the filename
              filename=$(basename "$file")
              timestamp="${filename:0:20}"  # Extracts '2024-03-17T02:51:25'

                # Convert timestamp to seconds since the Unix epoch
                file_time=$(date -u -d "$timestamp" +%s)

              # Calculate the difference in hours
              diff=$(( (current_time - file_time) / 3600 ))

              # Check if the difference is greater than 12 hours
              if [ "$diff" -gt 12 ]; then
                  echo "Deleting $file (older than 12 hours)"
                    rm "$file"
              fi
          done



      - name: Fetch feed data and save with timestamp
        run: |
          mkdir -p feed
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          FILENAME="feed/feed.json"
          curl "https://helldiverstrainingmanual.com/api/v1/war/news?from=2899330" -o "$FILENAME"

      - name: Cleanup old feed files in /feed
        run: |
          find feed/ -type f -name '*_feed.json' -mmin +40 -delete

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions Bot"
          git add data/ feed/
          git commit -m "Update data for war season ${{ steps.fetch-season.outputs.current_season }}" -a || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.ACTION_BOT_KEY }}@github.com/devpoole2907/helldivers-api-cache.git
          git push






